/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.classes.Person.Man;
import org.example.classes.Person.Person;
import org.example.classes.Person.PersonInvocationHandler;

import java.lang.reflect.Proxy;


public class App {

    public static void main(String[] args) {
        Man mohan = new Man("Mohan", 30, "Delhi", "India");
        ClassLoader mohanClassLoader = mohan.getClass().getClassLoader();
        Class[] interfaces = mohan.getClass().getInterfaces();
        Person proxymohan = (Person) Proxy.newProxyInstance(mohanClassLoader, interfaces, new PersonInvocationHandler(mohan));
        proxymohan.introduce(mohan.getName());
//       CgClass.main(args);
    }
}
